[package]
name = "hamheatmap-validation-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hamheatmap-app-service = { path = "../app-service" }
getrandom = "0.2.17"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"

[[bin]]
name = "hamheatmap-validation-server"
