# Ham Wireless View
# Project creator and lead developer: Arsenic-er
# SPDX-FileCopyrightText: 2026 Arsenic-er
# SPDX-License-Identifier: Apache-2.0

[package]
name = "hamheatmap-mvp"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hamheatmap-cache = { path = "../cache" }
hamheatmap-coverage = { path = "../coverage" }
hamheatmap-terrain = { path = "../terrain" }
